spring:
  application:
    name: User-Management-System
  datasource:
    url: jdbc:mysql://localhost:3306/ums
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
